language: ruby
rvm:
  - 2.2
cache:
  - bundler
before_install:
  - export TZ=Europe/Moscow
  - date
script: bundle exec rake build
branches:
  only:
    - master
deploy:
  provider: s3
  access_key_id: "$AWS_KEY_ID"
  secret_access_key: "$AWS_ACCESS_KEY"
  bucket: "www.juev.org"
  skip_cleanup: true
  region: "eu-west-1"
  acl: public_read
  local_dir: public
  detect_encoding: true
  cache_control: "max-age=0"

env:
  global:
  - secure: "LYHqtg9uHADutWkfaseQqoOPw6Y7QYUjhe1QHf2AkgD+RVIukLWjZj64sFdyTjrtKci0eIdPaMEQTZjBntxukWGQPq6hp42Cz6x/osVOjOK+SW6mtQkkP7B6GzkB3ZjwRJP1UprGzVuWaz0JsCK3vrdUVmYhLTsnwNw41b6i0PE="
  - secure: "Okp0ZCB7TWeAnwRUxjspf/BmLmbJzn6RurDP5943YgAjEgGbq5IiqYl9oXIzN7pfUr0d9IRXpupjOySV+YLqTmSk+SFhkEXOTnRaAhgvSrW/9f5+wIzkWwnQgDb08YXtCBjo3T85B7FMaR7bWI6BtJnEImHDdgPN7tPsK0S2hgw="
