language: ruby
rvm:
- 2.1
cache:
- apt
- bundler
addons:
  ssh_known_hosts: ssh.juev.org
  apt:
    packages:
    - libgsl0-dev
before_install:
- openssl aes-256-cbc -K $encrypted_d7becb892f62_key -iv $encrypted_d7becb892f62_iv
  -in deploy_rsa.enc -out $TRAVIS_BUILD_DIR/deploy_rsa -d
- export TZ=Europe/Samara
- date
script: bundle exec rake build
after_success:
- eval "$(ssh-agent -s)"
- chmod 600 $TRAVIS_BUILD_DIR/deploy_rsa
- ssh-add $TRAVIS_BUILD_DIR/deploy_rsa
- bundle exec rake publish
branches:
  only:
  - master
