language: ruby
rvm:
  - 2.1

cache:
  - apt
  - bundler

addons:
  apt:
    packages:
      - libgsl0-dev

script: bundle exec rake deploy

branches:
  only:
    - master

env:
  global:
    - secure: "Vubnw00gb0CJyQwdifGpbzS+LEYUD7vOYlutbtVNRJfGgYPMYmDGGpcj0azEipIqbewi2R9onspk5AGZX+RU1Hh2B3Y7QS2A8HHHgItxBy+KylGiaiPH+oc8jFdIXHIjLX7ojx1h7TIBxlMsyMxsZd5/ho8pKoe3Va1VThQ7CNhEInaVfki3q/0U6RKCOc0PxVOrTYhPjDqFWEqbaKOyMhkIZpQTjtB02yhoiyUMyR80kbJn3fT7hV88Uesg1Ld2NqpkG9bLjity47BQ5X1J3EmzbzXjJiteGTU4XPz1qL2f1jQ8WKLFQAUos8S3NBDpm+WIiT1lUUaEeOFT/g0s7isfHxOjhu3gJxrHcvCAHOKMktjV1xAVtOGKZoKSlnZha2BTbW7Lq/uIh4u0OOXiuA2XeD+KbzGDOa6rqkDlPddnhhRkGTixUJ3SkYDSwVSImdERsBDfALX0cPB8pHCtTZ3b1eOBvkXoLtWmEcMx7BCAZSZW9uW6t4FiIVZPJxhvWj+gOvvCaRHd3XF1Cm2/i6xSIiPVIKsHyvflFLTRvEByM0aqcxGDtVLtReRRthlvC/qzWh8faF2BouQn1Zc779dHgeTO2/T81IufyAyuNZtKBPpgXWQNfSxWW5ttb0k9JEpRLK7F+dudbqxBsky17AqmTkh/2lMNxsZKN9Xvh44="
    - secure: "vINFGWSa3uY92UzOiwXk/8cMZTORfz6Z3p1xhN08FrlS25jmZwxNtfqR88T07fNWiPAX+GG8hsDfDfJHkJ0RN0xDQxwpg+CEFf7oDLpBfDaEfeFrHR/qJnIz+1y89BkiZ7o36sYerAJ+s4yQy/IYP7CRqaMOL7ZF3jNJnoxfpuYkNgEFc5T/1vkyVUQZQCzuGxF/X/JBpkuGKNdOyT5WxsGGz1xC8mzvt+WL0DlznTl86nVLGv0rjhDGlG1amQV5W1V9f+4DVYEOcOMz4nO7EAdX+heOFm2F22pI9jo5+i7XCaNvWfrqAuUEUOsKYq2zJzjUY4Mszf16zurNG8p+6Vr8d2Z7+HYzVhSb3KgJa/zQ2/PtCE1Gurcx3meKm78xnSCbuosTW7fEVBMpiu0ibwGkRCl//+ekThQcTAeE4Gdthj4VcJjP8cCWwJ+AV2zI1M0qztFh1YQVt4OHp22bBwSohMj5qkpCJOnQJ44HDMDhEjIpU5kmo2pTHcPw7quHHOBtB8/3uaMNaHicMtOQd+4Ks1D9vUXfZrrxyiplR0ATdm3K3vfhY45S7CFdm9a94pN5XZw/RVNcMcBgGuxP66+BE34ATe3U4zL05x2WUMjFYZOKM6V5bFAzo6qtSHU0Kh0IM+DeXT7k1KvYDkAks6ru3XVYVSFqaqpVNbt67OQ="
    - secure: "K48twKAOFtP1CIkSawvGW1PU5Vvw1w7k1QheH3k8nN2BUUmT+BfezqPL0cBS/9zNrKUQAcp2aMfkJqzHSrFjRVk+wrVQUiGDlEG93D2WeTPjFfP49vHV/1MqmT7op+W39HnYEgwj1IvR0N6770tL0cqKU0fzeTR9tHWTgkMG2Ejzel5MbmKP2/7ZzEZBqY4lWSw/g93V8F/Csd7zYdH5KCjxMGluvm7UDZsB+HOc79mzmyNQX4DMPHQMmk/YuhvYo1a3i6x2NXP96XJr1mbXLrCzW4JFniQo1gWoqLXvuSuLtuMU+BxDw0G3MVWzDJDrQcvDnLlk16tpmGMMHtxeC26fYLBopE7puuV00z12oGSak21Uws6m2DuCoctR13J7pdLgVcaBheb4JGaIqwK+X9WXPtrCit6kXfpYMjWWDjVyxkc0ZxqcJewHwiii926iwBZ53eZOIxbl6pTCF7TyXro90i6ZVl1mVSKBT1R/XOGj+E20qZJMRbr9UMx7YX6FIp5GV+cFnAZ4hDJp5XybWNtC8yKxIQmRNRw/usEyFn5ko5PQ/tQd/VMpZ/qV0yeHvp2abguX563Ny+dInFIGxpbPO9Dn3kBZCin2B5JT5RBo+2D3pvVUihdp00aGRMr/zFyAA4s2pfGDh9cR/WS4X4vqaDg7Kt746hfWYDHuTUs="
