dist: trusty

language: ruby
rvm:
  - 2.6.0

cache:
  - bundler

before_install:
  - export TZ=Europe/Moscow
  - date
  - gem update --system
  - gem install bundler

script:
  - bundle exec rake build

deploy:
  provider: s3
  access_key_id: "<%= ENV['AWS_KEY_ID'] %>"
  secret_access_key: "<%= ENV['AWS_ACCESS_KEY'] %>"
  bucket: "juev.org"
  skip_cleanup: true
  region: "eu-west-1"
  detect_encoding: true

branches:
  only:
    - master

env:
  global:
  - secure: "LYHqtg9uHADutWkfaseQqoOPw6Y7QYUjhe1QHf2AkgD+RVIukLWjZj64sFdyTjrtKci0eIdPaMEQTZjBntxukWGQPq6hp42Cz6x/osVOjOK+SW6mtQkkP7B6GzkB3ZjwRJP1UprGzVuWaz0JsCK3vrdUVmYhLTsnwNw41b6i0PE="
  - secure: "Okp0ZCB7TWeAnwRUxjspf/BmLmbJzn6RurDP5943YgAjEgGbq5IiqYl9oXIzN7pfUr0d9IRXpupjOySV+YLqTmSk+SFhkEXOTnRaAhgvSrW/9f5+wIzkWwnQgDb08YXtCBjo3T85B7FMaR7bWI6BtJnEImHDdgPN7tPsK0S2hgw="
