---
url:         http://www.juev.ru
future:      true
lsi:         false
#pygments:    true
markdown:    kramdown
permalink:   pretty

root:        /
source:      source
destination: public
plugins:     plugins
pygments:    false # default python pygments have been replaced by pygments.rb

title: "Авторский проект Евсюкова Дениса"
description: "Wordpress, Jekyll, Ruby, PHP, Linux, Ubuntu, VPS и многое другое на страницах сайта."
keywords: "mac, tips, wordpress, jekyll, ruby, php, linux, ubuntu, vps, soft"

githuburl: "https://github.com/Juev/juev.ru/blob/master/source/_posts"
tag_page_layout: tag_page
tag_page_dir: tags
asset_pipeline:
  bundle: true            # Default = true
  compress: true          # Default = true
  output_path: assets     # Default = assets
  display_path: http://static.juev.ru/assets       # Default = nil
  gzip: false             # Default = false
