---
url:         https://www.juev.org
future:      true
lsi:         false
markdown:    kramdown
permalink:   pretty
incremental: false

root:        /
source:      source
destination: public
plugins_dir: plugins
highlighter: rouge

include:      ["_redirects", "_headers"]

kramdown:
  input: GFM
  syntax_highlighter: rouge

title: "Denis Evsyukov"
description: "Описание опыта использования различных программ и веб-сервисов. Личные рекомендации и критика."
keywords: "mac, tips, wordpress, jekyll, ruby, php, linux, ubuntu, vps, soft"

githuburl: "https://github.com/Juev/juev.ru/blob/master/source/_posts"
tag_page_layout: tag_page
tag_page_dir: tags

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      image: https://static.juev.org/images/calvin.png
