--- 
url: 	     http://www.juev.ru
future:      true
lsi:         false
#pygments:    true
markdown:    kramdown
permalink:   pretty

root:        /
source:      source
destination: public
plugins:     plugins
pygments:    false # default python pygments have been replaced by pygments.rb

description: "Wordpress, Jekyll, Ruby, PHP, Linux, Ubuntu, VPS и многое другое на страницах сайта."
keywords: "mac, tips, wordpress, jekyll, ruby, php, linux, ubuntu, vps, soft"
