--- 
exclude: [Rakefile, jekyll.pid, depl.sh]
url: 	     http://www.juev.ru
future:      true
lsi:         false
pygments:    true
markdown:    kramdown
permalink:   pretty

description: "Wordpress, Jekyll, Ruby, PHP, Linux, Ubuntu, VPS и многе другое на страницах сайта."
keywords: "wordpress,jekyll,ruby,php,linux,ubuntu,vps,soft"
