---
url:         https://www.juev.org
future:      false
lsi:         false
markdown:    kramdown
permalink:   pretty
incremental: false

timezone: Europe/Moscow

root:        /
destination: public
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

title: "Denis Evsyukov"
description: "Описание опыта использования различных программ и веб-сервисов. Личные рекомендации и критика."
keywords: "mac, tips, wordpress, jekyll, ruby, php, linux, ubuntu, vps, soft"

repository: "juev/juev.org"
words_per_minute: 150

githuburl: "https://github.com/juev/juev.ru/blob/master/source/_posts"

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      image: "https://static.juev.org/images/calvin.png"

# Reading Files
include:
  - _pages
  - _posts
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - /docs
  - /test
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
envs: development
