name: Github pages

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.2.2
        with:
          hugo-version: "0.62.0"
          extended: true
      - name: Build
        run: hugo --gc && rm -rf public/pages
      - name: Deploy
        run: |
          git init
          git add .
          git config --local user.email "action@github.com"
          git config --local user.name "Denis Evsyukov"
          git commit -m "Deploy to Github Pages"
          git push --force --set-upstream "https://${{ secrets.GITHAB_TOKEN }}@github.com/juev/juevorg-public.git" master > /dev/null 2>&1
        working-directory: public
      - uses: jakejarvis/cloudflare-purge-action@master
        env:
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
